map_server:
  ros__parameters:
    yaml_filename: ""        # launch에서 덮어씀
    frame_id: map
    topic_name: map
    use_sim_time: false

lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    bond_timeout: 0.0
    node_names: ['map_server']
